# File: wrangler.toml

[[kv_namespaces]]
binding = "SHORTLINKS" # Nama variabel yang akan digunakan di dalam fungsi
id = "ID_NAMESPACE_ANDA_DI_SINI" # ID namespace yang baru saja Anda buat

[[migrations]]
tag = "v1" # A version tag for this migration
new_classes = ["Everyone"] # Default.
